language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
script: "./travis-tool.sh run_tests"
on_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Ifs4aTa2yY98nF37JTIrWGDDIukH1am43ocHGMc/l/5sxtpvOaaoPMLsqoKO9jekATBbMuzPK8ZDMnFe8Zrjyoim63jWzGhr1I8zt6NVUtfrPGRAUrSrK6+MDMbinvKyV58cj/byURHcaM2qIi996s5kbU9X7qZA42V0Mpy6f0Q=
